[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17

lib_deps =
    m5stack/M5Unified
    m5stack/M5CoreS3
    knolleary/PubSubClient@^2.8